### ISSUE TITLE
Crash After using latest Sdk (2.5.2)

### ISSUE THREAD

**Issue by superdiazzz** [mumayank/AirLocation#27]
Hi mumayank,

I got crash after i update latest version of AirLocation SDK

stacktrace as below

```
Process: mobile.android.myapp, PID: 4356
                                                                                                    java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.SettingsClient, but class was expected (declaration of 'com.google.android.gms.location.SettingsClient' appears in /data/app/mobile.android.myapp-lcUiTnwLRisX1ykHFmfcUA==/base.apk!classes16.dex)
                                                                                                    	at mumayank.com.airlocationlibrary.helpers.LocationOptimizationPermissionHelper.getPermission(LocationOptimizationPermissionHelper.kt:29)
                                                                                                    	at mumayank.com.airlocationlibrary.AirLocation.getOptimizationPermissions(AirLocation.kt:138)
                                                                                                    	at mumayank.com.airlocationlibrary.AirLocation.checkIfInFlightMode(AirLocation.kt:129)
                                                                                                    	at mumayank.com.airlocationlibrary.AirLocation.access$checkIfInFlightMode(AirLocation.kt:20)
                                                                                                    	at mumayank.com.airlocationlibrary.AirLocation$airPermissions$1.invoke(AirLocation.kt:55)
                                                                                                    	at mumayank.com.airlocationlibrary.AirLocation$airPermissions$1.invoke(AirLocation.kt:20)
                                                                                                    	at mumayank.com.airpermissions.AirPermissions.request(AirPermissions.kt:47)
                                                                                                    	at mumayank.com.airlocationlibrary.AirLocation.getLocationPermissions(AirLocation.kt:118)
```

I have followed documentation for every steps, i believe there is no issue there. I think this issue only appears inside AirLocationsdk. Based on this [similar issue](https://github.com/mapbox/mapbox-maps-android/issues/1752) the problem might comes from google play service. 
Could you like to help me? thanks

**Comment by mumayank** [comment]
Sure, let me look into it and get back to you soon. Thanks for highlighting

**Comment by superdiazzz** [comment]
[https://developers.google.com/android/guides/releases#october_13_2022](https://developers.google.com/android/guides/releases#october_13_2022) @mumayank  for more information, hope you can solve

**Comment by superdiazzz** [comment]
Hi @mumayank kindly please update? i think i need this update as soon as posible

**Comment by mumayank** [comment]
Checked on Google Pixel and the issue could not be reproduced. Looks like this is a OEM-specific issue. Unfortunately, currently the lib doesn't support all OEMs.

**Comment by superdiazzz** [comment]
> Checked on Google Pixel and the issue could not be reproduced. Looks like this is a OEM-specific issue. Unfortunately, currently the lib doesn't support all OEMs.

I see, thanks mumayank

**Comment by ac23C** [comment]
I am facing the same issue
